services:
  app:
    image: popeye0618/comatching_fc:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    networks:
      - fc_backend

  mysql:
    image: mysql:8.0
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-test-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - fc_backend

  redis:
    image: redis:latest
    hostname: redis_fc
    container_name: redis_fc
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${SPRING_REDIS_PASSWORD} --port 6379
    volumes:
      - redis-test-data:/data  # Redis 볼륨 추가
    networks:
      - fc_backend

networks:
  fc_backend:

volumes:
  mysql-test-data:  # MySQL 볼륨
  redis-test-data:  # Redis 볼륨
